// Numeracja ksiąg (1-66) i ich polskie nazwy/skróty zgodne z jw.org (potwierdzone bezpośrednio
// na stronie biblioteki - https://www.jw.org/pl/biblioteka/biblia/biblia-wydanie-do-studium/ksiegi/,
// atrybut data-book + pola fullName/longAbbrName/abbrName). Ta sama numeracja jest używana w
// parametrze `bible=` linku do Finder (np. 19016011 = księga 19, rozdział 16, werset 11).
export const BIBLE_BOOKS = [
  { num: 1, full: 'Rodzaju', long: 'Rodz.', abbr: 'Rdz' },
  { num: 2, full: 'Wyjścia', long: 'Wyjścia', abbr: 'Wj' },
  { num: 3, full: 'Kapłańska', long: 'Kapł.', abbr: 'Kpł' },
  { num: 4, full: 'Liczb', long: 'Liczb', abbr: 'Lb' },
  { num: 5, full: 'Powtórzonego Prawa', long: 'Powt. Pr.', abbr: 'Pwt' },
  { num: 6, full: 'Jozuego', long: 'Joz.', abbr: 'Joz' },
  { num: 7, full: 'Sędziów', long: 'Sędz.', abbr: 'Sdz' },
  { num: 8, full: 'Rut', long: 'Rut', abbr: 'Rut' },
  { num: 9, full: '1 Samuela', long: '1 Sam.', abbr: '1Sm' },
  { num: 10, full: '2 Samuela', long: '2 Sam.', abbr: '2Sm' },
  { num: 11, full: '1 Królów', long: '1 Król.', abbr: '1Kl' },
  { num: 12, full: '2 Królów', long: '2 Król.', abbr: '2Kl' },
  { num: 13, full: '1 Kronik', long: '1 Kron.', abbr: '1Kn' },
  { num: 14, full: '2 Kronik', long: '2 Kron.', abbr: '2Kn' },
  { num: 15, full: 'Ezdrasza', long: 'Ezd.', abbr: 'Ezd' },
  { num: 16, full: 'Nehemiasza', long: 'Nehem.', abbr: 'Neh' },
  { num: 17, full: 'Estery', long: 'Est.', abbr: 'Est' },
  { num: 18, full: 'Hioba', long: 'Hioba', abbr: 'Hi' },
  { num: 19, full: 'Psalmy', long: 'Ps.', abbr: 'Ps' },
  { num: 20, full: 'Przysłów', long: 'Prz.', abbr: 'Prz' },
  { num: 21, full: 'Kaznodziei', long: 'Kazn.', abbr: 'Kzn' },
  { num: 22, full: 'Pieśń nad Pieśniami', long: 'Pieśń', abbr: 'PnP', extra: ['Pieśń'] },
  { num: 23, full: 'Izajasza', long: 'Izaj.', abbr: 'Iz' },
  { num: 24, full: 'Jeremiasza', long: 'Jer.', abbr: 'Jer' },
  { num: 25, full: 'Lamentacje', long: 'Lam.', abbr: 'Lam' },
  { num: 26, full: 'Ezechiela', long: 'Ezech.', abbr: 'Eze' },
  { num: 27, full: 'Daniela', long: 'Dan.', abbr: 'Dn' },
  { num: 28, full: 'Ozeasza', long: 'Oz.', abbr: 'Oz' },
  { num: 29, full: 'Joela', long: 'Joela', abbr: 'Jl' },
  { num: 30, full: 'Amosa', long: 'Am.', abbr: 'Am' },
  { num: 31, full: 'Abdiasza', long: 'Abd.', abbr: 'Abd' },
  { num: 32, full: 'Jonasza', long: 'Jon.', abbr: 'Jon' },
  { num: 33, full: 'Micheasza', long: 'Mich.', abbr: 'Mi' },
  { num: 34, full: 'Nahuma', long: 'Nahuma', abbr: 'Nah' },
  { num: 35, full: 'Habakuka', long: 'Hab.', abbr: 'Hab' },
  { num: 36, full: 'Sofoniasza', long: 'Sof.', abbr: 'Sof' },
  { num: 37, full: 'Aggeusza', long: 'Agg.', abbr: 'Ag' },
  { num: 38, full: 'Zachariasza', long: 'Zach.', abbr: 'Za' },
  { num: 39, full: 'Malachiasza', long: 'Malach.', abbr: 'Mal' },
  { num: 40, full: 'Mateusza', long: 'Mat.', abbr: 'Mt' },
  { num: 41, full: 'Marka', long: 'Marka', abbr: 'Mk' },
  { num: 42, full: 'Łukasza', long: 'Łuk.', abbr: 'Łk' },
  { num: 43, full: 'Jana', long: 'Jana', abbr: 'Jn' },
  { num: 44, full: 'Dzieje', long: 'Dzieje', abbr: 'Dz' },
  { num: 45, full: 'Rzymian', long: 'Rzym.', abbr: 'Rz' },
  { num: 46, full: '1 Koryntian', long: '1 Kor.', abbr: '1Ko' },
  { num: 47, full: '2 Koryntian', long: '2 Kor.', abbr: '2Ko' },
  { num: 48, full: 'Galatów', long: 'Gal.', abbr: 'Gal' },
  { num: 49, full: 'Efezjan', long: 'Efez.', abbr: 'Ef' },
  { num: 50, full: 'Filipian', long: 'Filip.', abbr: 'Flp' },
  { num: 51, full: 'Kolosan', long: 'Kol.', abbr: 'Kol' },
  { num: 52, full: '1 Tesaloniczan', long: '1 Tes.', abbr: '1Ts' },
  { num: 53, full: '2 Tesaloniczan', long: '2 Tes.', abbr: '2Ts' },
  { num: 54, full: '1 Tymoteusza', long: '1 Tym.', abbr: '1Tm' },
  { num: 55, full: '2 Tymoteusza', long: '2 Tym.', abbr: '2Tm' },
  { num: 56, full: 'Tytusa', long: 'Tyt.', abbr: 'Tyt' },
  { num: 57, full: 'Filemona', long: 'Filem.', abbr: 'Flm' },
  { num: 58, full: 'Hebrajczyków', long: 'Hebr.', abbr: 'Heb' },
  { num: 59, full: 'Jakuba', long: 'Jak.', abbr: 'Jak' },
  { num: 60, full: '1 Piotra', long: '1 Piotra', abbr: '1Pt' },
  { num: 61, full: '2 Piotra', long: '2 Piotra', abbr: '2Pt' },
  { num: 62, full: '1 Jana', long: '1 Jana', abbr: '1Jn' },
  { num: 63, full: '2 Jana', long: '2 Jana', abbr: '2Jn' },
  { num: 64, full: '3 Jana', long: '3 Jana', abbr: '3Jn' },
  { num: 65, full: 'Judy', long: 'Judy', abbr: 'Judy' },
  { num: 66, full: 'Objawienie', long: 'Obj.', abbr: 'Obj' },
]
